export const ResortStatusType = {
    FORM_COMPLETED: 'FORM_COMPLETED',
    IMAGES_ADDED: 'IMAGES_ADDED',
    LOCATION_ADDED: 'LOCATION_ADDED',
    REQUESTED_APPROVAL: 'REQUESTED_APPROVAL',
    APPROVAL_REJECTED: 'APPROVAL_REJECTED',
    ADMIN_APPROVED: 'ADMIN_APPROVED',
}